### ISSUE TITLE
list model

### ISSUE THREAD

**Issue by RyanBin0126** [im-perativa/streamlit-calendar-demo#1]
When I used ”list“ model and clicked the event，then error happened.
No matter in the online demo or in my local environment.

The error like this:
Component Error
Converting circular structure to JSON --> starting at object with constructor 'HTMLDivElement' | property '__reactInternalInstance$i4o8rs9dx7q' -> object with constructor 'Hl' --- property 'stateNode' closes the circle****

**Comment by im-perativa** [comment]
Closed at https://github.com/im-perativa/streamlit-calendar/issues/5
