### ISSUE TITLE
Is there any way to get the calendar to go Monday - Sunday

### ISSUE THREAD

**Issue by R33s3** [im-perativa/streamlit-calendar-demo#2]
I have an odd need to make the calendar weeks start on Monday for a scheduling app I am building. I incorporated this into my app and everyone loves it.  Just wondering if there is a way to adjust the calendar and associated views to go Monday through Sunday?

**Comment by im-perativa** [comment]
Hi @R33s3 you can use `"firstDay": 1` in `options` dictionary as shown in FullCalendar docs [here](https://fullcalendar.io/docs/firstDay) as this component uses the same options configuration
